### ISSUE TITLE
Heroku complains about  Deprecated or unsupported version of go (go1.6.4)

### ISSUE THREAD

**Issue by koppor** [y-yagi/gradle-update-notification#12]
Heroku complains about  Deprecated or unsupported version of go (go1.6.4)

<details>

-----> Go app detected

-----> Fetching jq... done

-----> Checking Godeps/Godeps.json file.

 !!    

 !!    Deprecated or unsupported version of go (go1.6.4)

 !!    See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.

 !!    

-----> Installing go1.6.4

-----> Fetching go1.6.4.linux-amd64.tar.gz... done

 !!    Installing package '.' (default)

 !!    

-----> Running: go install -v -tags heroku . 

github.com/y-yagi/gradle-update-notifier/vendor/github.com/codegangsta/cli

github.com/y-yagi/gradle-update-notifier/vendor/github.com/google/go-querystring/query

github.com/y-yagi/gradle-update-notifier/vendor/github.com/google/go-github/github

github.com/y-yagi/gradle-update-notifier/vendor/github.com/pkg/errors

github.com/y-yagi/gradle-update-notifier/vendor/golang.org/x/net/context

github.com/y-yagi/gradle-update-notifier/vendor/golang.org/x/oauth2/internal

github.com/y-yagi/gradle-update-notifier/vendor/golang.org/x/oauth2

github.com/y-yagi/gradle-update-notifier

-----> Discovering process types

       Procfile declares types -> web

-----> Compressing...

       Done: 3.1M

-----> Launching...

       Released v4

       https://jabref-update-notification.herokuapp.com/ deployed to Heroku

</details>

**Comment by y-yagi** [comment]
Thanks for creating an issue.I fixed it. It works in the master branch.
Even when there is time, please try again. Thanks!
